spring.application.name=OtpService
# Server
server.port=8082




# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shahbazmurat@gmail.com
spring.mail.password=sunl fkjt hzcn drrj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000ms

# Services URLs
services.user.url=http://localhost:8081



# Logging
logging.level.az.jet.otpservice=DEBUG
logging.level.org.springframework.mail=DEBUG
